---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dashaun-tanzu/saa-concourse-pipelines-demo
      branch: main
  - name: docker-image
    type: docker-image
    source:
      repository: ((docker-hub-username))/scpd-runner
      username: ((docker-hub-username))
      password: ((docker-hub-password))

jobs:
  - name: build-and-publish
    public: true
    plan:
      - get: source-code
        trigger: true
      - put: docker-image
        params:
          build: source-code
          dockerfile: source-code/docker/Dockerfile
          tag_file: source-code/.git/ref
          tag_as_latest: true