---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dashaun-tanzu/saa-concourse-pipelines-demo
      branch: main
  - name: docker-image
    type: docker-image
    source:
      repository: ((docker-hub-username))/scpd-runner
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      tag: latest

jobs:
  - name: build-and-publish
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: build-docker-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/oci-build-task
              tag: latest
          inputs:
            - name: source-code
          outputs:
            - name: image
          params:
            CONTEXT: source-code
            DOCKERFILE: source-code/docker/Dockerfile
          run:
            path: build

      - put: docker-image
        params:
          image: image/image.tar
          additional_tags: source-code/.git/ref
          tag_as_latest: true
