resource_types:
  - name: time
    type: registry-image
    source: { repository: concourse/time-resource }

resources:
  - name: every-3h
    type: time
    source:
      interval: 3h

  - name: repo
    type: git
    source:
      uri: ((repo_clone_url))
      branch: main
      username: x-access-token
      password: ((github_token))

jobs:
  - name: run-rewrite
    serial: true
    plan:
      - get: every-3h
        trigger: true
      - get: repo
      - task: recipe-runner
        config:
          caches:
          - path: /tmp/shared-binaries
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
            - name: repo
          params:
            GITHUB_TOKEN: ((github_token))
            REPO_FULL_NAME: ((repo_full_name))
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Running recipe-"
                ls -latr /tmp/shared-binaries
