resource_types:
  - name: time
    type: registry-image
    source: { repository: concourse/time-resource }
resources:
  - name: ubuntu
    type: registry-image
    source:
      repository: ((docker-hub-username))/scpd-runner
      username: ((docker-hub-username))
      password: ((docker-hub-password))
  - name: periodic
    type: time
    source:
      interval: 12h
  - name: repo
    type: git
    source:
      uri: ((repo_clone_url))
      branch: main
      username: x-access-token
      password: ((github_token))
jobs:
  - name: detect-drift
    serial: true
    plan:
      - get: periodic
        trigger: true
      - get: repo
      - get: ubuntu
      - task: recipe-runner
        image: ubuntu
        config:
          platform: linux
          inputs:
            - name: repo
          params:
            GIT_TOKEN_FOR_PRS: ((github_token))
            REPO_FULL_NAME: ((repo_full_name))
            MAVEN_PASSWORD: ((maven_password))
            MAVEN_USERNAME: ((maven_username))
            SPRING_ADVISOR_MAPPING_CUSTOM_0_GIT_URI: https://github.com/dashaun-tanzu/advisor-mappings.git
            SPRING_ADVISOR_MAPPING_CUSTOM_0_GIT_PATH: .advisor/mappings/
          run:
            path: bash
            args:
              - -lc
              - |
                set -Eeo pipefail
                until curl -L -H "Authorization: Bearer $MAVEN_PASSWORD" \
                  -o advisor-cli.tar \
                  -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/1.4.0/application-advisor-cli-linux-1.4.0.tar; do
                  echo "Retrying..."
                  sleep 1
                done
                tar -xf advisor-cli.tar
                mv cli-binary/advisor ./
                cd repo
                sed -i "s/MAVEN_USERNAME/$MAVEN_USERNAME/g" /root/.m2/settings.xml
                sed -i "s/MAVEN_PASSWORD/$MAVEN_PASSWORD/g" /root/.m2/settings.xml
                echo $GIT_TOKEN_FOR_PRS | gh auth login --with-token
                if [[ $(gh pr list --state open --json number | jq length) -eq 0 ]]; then
                  echo "No open PRs found"
                else
                  echo "Open PRs found - task successful"
                  exit 0
                fi
                
                source "$HOME/.sdkman/bin/sdkman-init.sh"
                if [[ -f ".sdkmanrc" ]]; then
                  # sdk env install
                  sdk install java 21.0.6-librca
                  sdk default java 21.0.6-librca
                  sdk use java 21.0.6-librca
                else
                  sdk install java 21.0.6-librca
                  sdk default java 21.0.6-librca
                  sdk use java 21.0.6-librca
                fi
                cd ..
                chmod +x ./advisor
                ./advisor -version
                install ./advisor /usr/local/bin
                advisor -version
                cd repo
                ls
                echo "build config"
                advisor build-config get
                echo "upgrade plan"
                advisor upgrade-plan get
                echo "apply"
                advisor upgrade-plan apply --push
