resource_types:
  - name: time
    type: registry-image
    source: { repository: concourse/time-resource }
resources:
  - name: ubuntu
    type: registry-image
    source:
      repository: ubuntu
      username: ((docker-hub-username))
      password: ((docker-hub-password))
  - name: periodic
    type: time
    source:
      interval: 12h
  - name: repo
    type: git
    source:
      uri: ((repo_clone_url))
      branch: main
      username: x-access-token
      password: ((github_token))
jobs:
  - name: detect-drift
    serial: true
    plan:
      - get: periodic
        trigger: true
      - get: repo
      - get: ubuntu
      - task: check-pull-requests
        image: ubuntu
        config:
          platform: linux
          inputs:
            - name: repo
          params:
            GITHUB_TOKEN: ((github_token))
            REPO_FULL_NAME: ((repo_full_name))
          run:
            path: bash
            args:
              - -lc
              - |
                set -Eeo pipefail
                export DEBIAN_FRONTEND=noninteractive
                apt update && apt install -y curl jq
                
                echo "Checking for open pull requests in ${REPO_FULL_NAME}..."
                
                # Get open pull requests from GitHub API
                PR_RESPONSE=$(curl -s \
                  -H "Authorization: Bearer $GITHUB_TOKEN" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${REPO_FULL_NAME}/pulls?state=open")
                
                # Check if there are any PRs
                PR_COUNT=$(echo "$PR_RESPONSE" | jq '. | length')
                
                if [ "$PR_COUNT" -eq 0 ]; then
                  echo "No open pull requests found."
                else
                  echo "Found $PR_COUNT open pull request(s):"
                  echo "=================================="
                
                  # Extract and display PR titles
                  echo "$PR_RESPONSE" | jq -r '.[] | "- PR #\(.number): \(.title)"'
                
                  echo "=================================="
                  echo "Pull request details:"
                  echo "$PR_RESPONSE" | jq -r '.[] | "PR #\(.number): \(.title)\n  Author: \(.user.login)\n  Created: \(.created_at)\n  URL: \(.html_url)\n"'
                fi
      - task: recipe-runner
        image: ubuntu
        config:
          platform: linux
          inputs:
            - name: repo
          params:
            GITHUB_TOKEN: ((github_token))
            REPO_FULL_NAME: ((repo_full_name))
            ARTIFACTORY_TOKEN: ((maven_password))
          run:
            path: bash
            args:
              - -lc
              - |
                set -Eeo pipefail
                export DEBIAN_FRONTEND=noninteractive
                apt update && apt install -y curl tar zip unzip
                curl -s "https://get.sdkman.io?ci=true" | bash
                source "/root/.sdkman/bin/sdkman-init.sh"
                until curl -L -H "Authorization: Bearer $ARTIFACTORY_TOKEN" \
                  -o advisor-cli.tar \
                  -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/1.4.0/application-advisor-cli-linux-1.4.0.tar; do
                  echo "Retrying..."
                  sleep 1
                done
                tar -xf advisor-cli.tar
                mv cli-binary/advisor ./
                cd repo
                if [[ -f ".sdkmanrc" ]]; then
                  sdk env install
                else
                  sdk install java 21.0.2-graalce
                  sdk use java 21.0.2-graalce
                fi
                cd ..
                chmod +x ./advisor
                ./advisor build-config get --path=./repo
                cat ./repo/target/.advisor/build-config.json
