resource_types:
  - name: time
    type: registry-image
    source: { repository: concourse/time-resource }
resources:
  - name: alpine
    type: registry-image
    source:
      repository: alpine
      username: ((docker-hub-username))
      password: ((docker-hub-password))
  - name: periodic
    type: time
    source:
      interval: 12h
  - name: repo
    type: git
    source:
      uri: ((repo_clone_url))
      branch: main
      username: x-access-token
      password: ((github_token))
jobs:
  - name: detect-drift
    serial: true
    plan:
      - get: periodic
        trigger: true
      - get: repo
      - get: alpine
      - task: recipe-runner
        config:
          platform: linux
          image: alpine
          inputs:
            - name: repo
          params:
            GITHUB_TOKEN: ((github_token))
            REPO_FULL_NAME: ((repo_full_name))
            ARTIFACTORY_TOKEN: ((maven_password))
          run:
            path: sh
            args:
              - -exc
              - |
                set -e
                apk add --no-cache curl tar
                until curl -L -H "Authorization: Bearer $ARTIFACTORY_TOKEN" -o advisor-cli.tar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/1.4.0/application-advisor-cli-linux-1.4.0.tar; do
                  echo "Retrying..."
                  sleep 1
                done
                tar -xf advisor-cli.tar
                mv cli-binary/advisor ./
                chmod +x ./advisor
                ./advisor build-config get --path=./repo
                cat ./repo/target/.advisor/build-config.json